### PR TITLE
Change default highlight level and fix Null Pointers

### LINKED ISSUE #8: Default highlighting for diagnostics does not match VS Code
When a language server does not set a severity on a diagnostic we default to INFO. On IntelliJ this means no highlighting on screen. 
image

It would be better to mimic VS Code which displays a red underline just to make sure the diagnostic is obvious. If the language server sets a certain severity we should honour that.

### PR DESCRIPTION
**Pull request by turkeylurkey**
Fixes #8 

image

Also: fix the problem where diagnostics, completion and quick fixes do not appear due to null pointer exceptions.

### CODE REVIEW

**Comment by turkeylurkey** [comment]
This fix pulled in the null checks previously added to handle language servers that do not supply the fields being checked. That is, you should also be able to review these null checks as well to ensure they do not change the behaviour (except prevent exceptions) and break anything. Let me know if I should rebase this just to include the highlight fix.

File: src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java [hunk 1]
```diff
@@ -127,9 +127,11 @@ private void addCompletionItems(PsiFile file, Editor editor, CompletionPrefix co
             // Create lookup item
             var lookupItem = createLookupItem(file, editor, completionPrefix.getCompletionOffset(), item, itemDefaults, languageServer);
             // Group it by using completion item kind
-            var groupedLookupItem = PrioritizedLookupElement.withGrouping(lookupItem, item.getKind().getValue());
+            int group = item.getKind() == null ? 0 : item.getKind().getValue();
```
Comment (mrglavas) [inline src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java:130]: So this avoids a `NullPointerException` but what does `0` mean here? When I look at https://github.com/eclipse-lsp4j/lsp4j/blob/main/org.eclipse.lsp4j/src/main/java/org/eclipse/lsp4j/CompletionItemKind.java all of the values returned by the `enum` are from 1 to 25.

Comment (turkeylurkey) [reply src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java:130]: Good question. It gets put in a field in a new object and who knows how that is interpreted? I was thinking "unknown" but would Text(1) be a better default? I assume that is a pretty generic category.

**Review by TrevCraw — APPROVED** [review]

File: src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java (hunk 1 above)
Comment (mrglavas) [reply src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java:130]: It was just an observation, but seemed like the default should be one of the defined values. It was the first time I'd looked at any of this and not familiar with this code so your guess is as good as mine. Assuming that it should be one of the values from the enum, I would suggest referencing the constant instead of the integer (e.g. `Text.getValue()` instead of `1`).

Comment (angelozerr) [reply src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java:130]: I suggest that you see our LSP4IJ, we remove this code since sort should be never done by grouping item with kind but by using sortText.

Comment (turkeylurkey) [reply src/main/java/org/microshed/lsp4ij/operations/completion/LSPCompletionContributor.java:130]: Ok, this point will be moot in the next update.
